version: 2

project_name: toney
release:
  github:
    owner: SourcewareLab 
    name: toney

builds:
  - id: toney
    main: . 
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - netbsd
      - openbsd
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    binary: toney

archives:
  - id: archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: toney 
    github:
      owner: SourcewareLab 
      name: toney
      branch: dev
    folder: Formula
    description: "Toney - a fast, lightweight terminal-based note-taking app"
    homepage: https://sourcewarelab.github.io/Toney/
    commit_author:
      name: NucleoFusion 
      email: lakshit.singh.mail@gmail.com 
    install: |
      bin.install "toney"

scoop:
  name: toney
  folder: scoop 
  description: "Toney - a fast, lightweight terminal-based note-taking app"
  homepage: https://sourcewarelab.github.io/Toney/
  bucket:
    name: toney
    owner: SourcewareLab
    branch: dev 
    commit_author:
      name: NucleoFusion
      email: lakshit.singh.mail@gmail.com

snapcrafts:
  - name: toney
    summary: "Fast, lightweight terminal-based note-taking app"
    description: |
      Toney is a fast, lightweight and extensible note-taking app that works directly from your terminal.
    confinement: classic
    grade: stable
    license: MIT

nfpms:
  - id: deb
    formats:
      - deb
    section: utils
    priority: optional
    maintainer: "NucleoFusion <lakshit.singh.mail@gmail.com>"
    description: "Toney - a fast, lightweight terminal-based note-taking app"
    license: MIT
    vendor: NucleoFusion
    homepage: https://sourcewarelab.github.io/Toney/

  - id: rpm
    formats:
      - rpm
    section: utils
    priority: optional
    maintainer: "NucleoFusion <lakshit.singh.mail@gmail.com>"
    description: "Toney - a fast, lightweight terminal-based note-taking app"
    license: MIT
    vendor: NucleoFusion
    homepage: https://sourcewarelab.github.io/Toney/

checksum:
  name_template: 'checksums.txt'


